### PR TITLE
chore: Use correct Mapbox Java SDK version

### LINKED ISSUE #2088: Fix Mapbox Java SDK version
**Describe the chore**
Mapbox Java SDK version is set to 4.9.0 while the latest release is 4.8.0.
https://github.com/mapbox/mapbox-java/releases

**Would you like to work on the issue?**
- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by ShridharGoel**
Fixes #2088

### CODE REVIEW

**Comment by ShridharGoel** [comment]
> How the project was syncing with the gradle files earlier if the version is not available?

It wasn't syncing so I checked and got to know that the version is not available. It was updated few days back (#2049). Don't know how Travis build is passing.

**Comment by iamareebjamal** [comment]
https://travis-ci.org/fossasia/open-event-attendee-android/builds/553816252?utm_source=github_status&utm_medium=notification

**Comment by ShridharGoel** [comment]
> If the latest version is 4.8.0, how did dependabot update it to 4.9.0 and how did the builds succeed?
> 
> All builds are still succeeding

Yes but isn't building locally. Would be good if anyone can confirm. 
Check the latest release version: https://github.com/mapbox/mapbox-java/releases

**Comment by iamareebjamal** [comment]
They have not tagged a release but released it on maven. Paste the error you're getting building locally

**Comment by ShridharGoel** [comment]
> Paste the error you're getting building locally

`ERROR: Failed to resolve: com.mapbox.mapboxsdk:mapbox-sdk-services:4.9.0`

**Pull request merged**
