### PR TITLE
Deep linking fixes

### LINKED ISSUE #2292: App link intent appear when clicking on Terms and Policy Section
**Describe the bug**
App deep linking appear when clicking on Terms and Policy Section

**Screenshots**
ezgif-1-183909d052bc

**Would you like to work on the issue?**
Open to all

### PR DESCRIPTION
**Pull request by rajput2122**
Fixes #2292 

Changes: minor changes in setting.xml file

Screenshots for the change:
[2019_08_28_14_21_12.zip](https://github.com/fossasia/open-event-attendee-android/files/3550193/2019_08_28_14_21_12.zip)

Debug apk: (for test)
[debug.zip](https://github.com/fossasia/open-event-attendee-android/files/3550207/debug.zip)

### CODE REVIEW

**Comment by ShridharGoel** [comment]
You have pushed wrong commits, check the `Files changed` section.

**Comment by ShridharGoel** [comment]
Also go through the following: 
https://blog.fossasia.org/open-source-developer-guide-and-best-practices-at-fossasia/
https://chris.beams.io/posts/git-commit/

Follow commit guidelines.

**Comment by ShridharGoel** [comment]
Also, add screenshots directly instead of adding a zip file.

**Comment by rajput2122** [comment]
Sorry sir

**Comment by liveHarshit** [comment]
> Also, add screenshots directly instead of adding a ZIP file.

GIF in this case

**Pull request closed without merging**
