### PR TITLE
fix: Scrolling in "Like event dialog"

### LINKED ISSUE #2632: Layout of "Sign in to like event"
**Describe the bug**
There is no scrolling in "Sign in to like event" dialog, this makes problem for user if using app in landscape mode.

**To Reproduce**
1. Go to Events, when user is not logged in
2. Click on like event button in landscape mode
3. Try to Scroll down

**Expected behavior**
The view should scroll smoothly so that user can see the layout perfectly

**Screenshots**
bug_like_login

**Smartphone Info:**

|               | |
|---------------|-|
|Device         |Redmi Note 4|
Android Version|Nougat 7.0  |

**Would you like to work on the issue?**

- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by dheerajkotwani**
Fixes #2632 Scrolling login to like event dialog

Changes: 
Added scroll bars to login to like event so user can use app smoothly in landscape mode too.

Screenshots for the change:
fix_like_login

### CODE REVIEW

**Review by nikit19 — APPROVED** [review]

**Comment by iamareebjamal** [comment]
Can we please fix all scrolling bugs in 1 PR

**Comment by dheerajkotwani** [comment]
> 
> 
> Can we please fix all scrolling bugs in 1 PR

okay i'll take care in future.

**Comment by liveHarshit** [comment]
> > Can we please fix all scrolling bugs in 1 PR
> 
> okay i'll take care in future.

Can you do that in this PR itself?

**Comment by dheerajkotwani** [comment]
> Can you do that in this PR itself?

there are no more issues related to scrolling for now

**Review by liveHarshit — APPROVED** [review]

**Pull request merged**
