### PR TITLE
chore: Version code, name and changelog for minor release 0.7.0

### PR DESCRIPTION
**Pull request by liveHarshit**

### CODE REVIEW

**Comment by liveHarshit** [comment]
> A lot of changes have gone into development branch. It is not 0.6 PATCH version anymore. It's 0.7

:+1:

**Comment by liveHarshit** [comment]
Updated

**Comment by liveHarshit** [comment]
@iamareebjamal Please remove skipping screenshots also.

**Comment by iamareebjamal** [comment]
Add a PR

**Comment by liveHarshit** [comment]
> Add a PR

 Already reverted https://github.com/fossasia/open-event-attendee-android/pull/2226/files

**Comment by iamareebjamal** [comment]
Add a PR fo this `Please remove skipping screenshots also.`

**Comment by liveHarshit** [comment]
> Add a PR fo this `Please remove skipping screenshots also.`

Yes same answer,  please check the changes - https://github.com/fossasia/open-event-attendee-android/pull/2226/files

**Comment by iamareebjamal** [comment]
Then why did you say `Please remove skipping screenshots also.`?

**Comment by liveHarshit** [comment]
> Then why did you say `Please remove skipping screenshots also.`?

Because that commit is added by you in that PR and merged, I was not aware of it. I just saw last commit on the master branch.

**Comment by liveHarshit** [comment]
https://github.com/fossasia/open-event-attendee-android/pull/2226/commits/276ef5ea90047f784b028f9d968aaa558b5bdff6

**Pull request merged**
