### PR TITLE
fix: App crash when no location found

### PR DESCRIPTION
**Pull request by anhanh11001**
Fixes: #2255

Screenshots for the change:
ezgif-5-64aa352a246e

### CODE REVIEW

**Comment by liveHarshit** [comment]
Fix build

**Comment by anhanh11001** [comment]
> Fix build

fixed

**Comment by anhanh11001** [comment]
LocationServiceImpl file changed here is for fdroid build. I don't know why fdroid and release build has a different implementation on LocationServiceImpl. In release build, a listener to LocationCallback is used for choosing the location near me instead of LocationListener like fdroid @liveHarshit

**Comment by liveHarshit** [comment]
@anhanh11001 We are using google services with location manager for play store build for fetching faster and for fdroid build, only location manager is used.

**Comment by anhanh11001** [comment]
@liveHarshit fixed

**Pull request merged**
