### PR TITLE
Fix: Deep linking issue resolved

### LINKED ISSUE #2292: App link intent appear when clicking on Terms and Policy Section
**Describe the bug**
App deep linking appear when clicking on Terms and Policy Section

**Screenshots**
ezgif-1-183909d052bc

**Would you like to work on the issue?**
Open to all

### PR DESCRIPTION
**Pull request by rajput2122**
Fixes #2292 
Changes: Removed intent filter of category browsable of MainActivity from AndroinManifest.xml file

Screenshots for the change:

### CODE REVIEW

**Comment by liveHarshit** [comment]
Also, do not send multiple PR for the same issue by next time!

**Comment by rajput2122** [comment]
> Great! You removed the whole feature for app link intents.

Sorry sir,i am trying. Can you please give little guidance ?

**Comment by liveHarshit** [comment]
> > Great! You removed the whole feature for app link intents.
> 
> Sorry sir,i am trying. Can you please give little guidance ?

First, check how it is implemented in the app, and from android documentation, then try to solve it.

**Comment by liveHarshit** [comment]
Modified the issue title.

**Comment by liveHarshit** [comment]
fixed

**Pull request closed without merging**
