### PR TITLE
chore: Add Chinese (Simplified) Language!

### LINKED ISSUE #2570: Add Chinese (Simplified) Language
**Describe the feature you'd like**

As many of FOSSASIA's software is primarily used in Asia, and thus China, adding the Chinese language as an option for users would greatly benefit many, especially the attendees of events in those countries.

**Would you like to work on the issue?**

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by pranavkarthik10**
Fixes #2570 

Changes: 
Added the Chinese simplified language for many users whose primary language is this. This was done using Google Translate and with lots of checking from my friends and a teacher who's native language is Chinese.

Screenshots for the change:
Screenshot_20200117-225951_Eventyay Attendee
Screenshot_20200117-230019_Eventyay Attendee
Screenshot_20200117-230012_Eventyay Attendee

### CODE REVIEW

**Review by nikit19 — APPROVED** [review]

**Comment by pranavkarthik10** [comment]
@nikit19 Thank you! Please merge it as well.

**Comment by cweitat** [comment]
This PR shouldn't merge at all! Are you sure you checked with your teacher? I spot so many mistakes

**Comment by cweitat** [comment]
file name does not follow international ISO language shortcode

**Comment by pranavkarthik10** [comment]
@cweitat Sorry about that, I tried my best with the translation for the most part. About the file name, it must be in this format as per android localization guides.

**Comment by iamareebjamal** [comment]
I feel the same way for all the translations added. There is no point of adding translations by copy pasting from Google Translate. I would not merge any translations, but unfortunately, it is a GCI task. It is better for the app to be untranslated than to have wrong translations

I don't know how an Indian can add chinese and thai translations

**Pull request merged**
