### PR TITLE
chore: Revert Translation PRs

### LINKED ISSUE #2581: Revert Translation PRs
Revert #2568, #2566 as there is no guarantee of correct language translation.

### PR DESCRIPTION
**Pull request by hoangdatngo**
Fixed: #2581 
Revert #2568, #2566 
As said by @cweitat , this doesn't have perfect meaning of translation.. and should be reverted

### CODE REVIEW

**Comment by iamareebjamal** [comment]
Where is said that polish translations are not good?
If you are polish, and find the translations to be bad, I'll merge it

**Comment by hoangdatngo** [comment]
@cweitat said to revert these two PR.

**Comment by iamareebjamal** [comment]
Where?

**Comment by hoangdatngo** [comment]
Here:
revert

**Comment by iamareebjamal** [comment]
Thank you

**Review by iamareebjamal — APPROVED** [review]

**Comment by hoangdatngo** [comment]
@iamareebjamal Thanks a lot sir

**Pull request merged**
