### PR TITLE
chore: Release v0.6.1

### PR DESCRIPTION
**Pull request by iamareebjamal**

### CODE REVIEW

**Comment by liveHarshit** [comment]
It should merge after PR #2185 There is a crash in the feedback section

**Comment by liveHarshit** [comment]
Changelogs 13.txt should also add!

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/open-event-attendee-android/pull/2200/commits/489afd3477e117d034636913e46acb680d05ae0d

**Comment by iamareebjamal** [comment]
> It should merge after PR #2185 There is a crash in the feedback section

Then finalize it ASAP

**Comment by iamareebjamal** [comment]
spotless errors

**Comment by liveHarshit** [comment]
> spotless errors

Fixed in PR #2185 :+1:

**Pull request merged**
