### PR TITLE
feat: Added Rating Dialog

### LINKED ISSUE #2583: Adding new rating system so user's can review the application
**Describe the feature you'd like**
Usually applications like Google Maps etc have a dialog which asks the users if they want to review the application. I would be nice to have it as most of the user don't bother to rate the application not because they don't want to but theywould have to go to the play store and open application page view then  review it.

**Screenshots**
Not really required

**Additional context**
This rating would give developers more options to read the rating and work on the issue

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

### LINKED ISSUE #2584: Chore: Upgrade Dependencies and sdk version
**Describe the chore**
Upgrade the dependecy of stripe etc. and also upgrade the targetsdkversion and compiled version to 29 (google recommends doing this)

**Would you like to work on the issue?**
- [x] Yes
- [ ] No
- Other:

### PR DESCRIPTION
**Pull request by scixor**
- Fixes #2583 

## Changes: 
- Added Rating System dialog for Google play builds by 
[lopspower](https://github.com/lopspower/RateBottomSheet)
> Note: Do not upgrade the dependency version to more than 1.0.2 because the builds fail in Kotlin check

## Screenshots for the change:
Screenshot_20200121-050254
Screenshot_20200121-050300
Screenshot_20200121-050306

## APK for testing
I have turned on `.setDebugForceOpenEnable(true)` although I have no idea if
```
 if (BuildConfig.FLAVOR== PLAY_STORE_BUILD_FLAVOR) {
```
will let it work 😕 
[app-fdroid-debug.zip](https://github.com/fossasia/open-event-attendee-android/files/4089510/app-fdroid-debug.zip)

### CODE REVIEW

**Comment by scixor** [comment]
@liveHarshit @iamareebjamal Please review 😇

**Comment by iamareebjamal** [comment]
1 PR for 1 issue

**Comment by scixor** [comment]
@iamareebjamal I have made different Commits for them 😇 is that not possible?

**Comment by iamareebjamal** [comment]
No

**Comment by scixor** [comment]
I will get the gradle one out in different pr then 😇

**Comment by scixor** [comment]
@iamareebjamal @liveHarshit all changes done.. I hope I get the linting right this time 😅

**Comment by scixor** [comment]
all the tests have passed 😀

**Review by jayasanka-sack — APPROVED** [review]

**Comment by scixor** [comment]
@liveHarshit @iamareebjamal it would be nice to have a review ... I think this implementation has no issues 😀

**Comment by iamareebjamal** [comment]
It's very annoying and we don't need this

**Comment by scixor** [comment]
>APK for testing
I have turned on `.setDebugForceOpenEnable(true)` although I have no idea if

are you talking about the apk? it is set to be in debug mode so that it pops up everytime otherwise there is no way to test this.. the current version has that mode shut off😇 so it asks only one time after 3 days of installation .. either the user can dismiss it forever or review it or ask it to pop up later

**Review by liveHarshit — COMMENTED** [review]
The dialog is there when you complete an order. No need for this on the home screen. You can check Eventbrite for this.

**Comment by liveHarshit** [comment]
https://github.com/fossasia/open-event-attendee-android/pull/2017

**Comment by scixor** [comment]
@liveHarshit I knew about that feature when I was exploring the registration UI.
 
I would assume most people might have used web to register, in that case, the person never registers on the android side... and then he logs into attendee app when the person in on the go, for map location event info etc because this app is very handy in that case 😇.

I definitely would do that, everytime because if I know about an event from lets say even fossasia's website, which says eventyay is hosting the tickets. I will search in google I will go to eventyay's  website, I will register there, then maybe somehow I will find out about the application in android which is more accessible, so I will download it.

this is the usecase in general 😀

**Comment by scixor** [comment]
I would say we can change the registration one too with this type of dialog/snackbar, as it is a snackbar basically, which isn't that "On the face", and directly redirects to the playstore

**Pull request closed without merging**
