### PR TITLE
fix: Included tax for tickets

### LINKED ISSUE #2233: Handle tax for included price and free tickets
**Would you like to work on the issue?**

yes

### PR DESCRIPTION
**Pull request by liveHarshit**
Fixes #2233 

<p align="center">
 
 
</p>
<p align="center">
 
 
</p>

### CODE REVIEW

**Comment by liveHarshit** [comment]
> When showing price of ticket in tax included, you have to reduce the tax from it.
> 
> Ticket : 100
> 
> Price: 91
> 
> Tax: 9
> 
> If I understand it correctly

Yes but I was not sure about is on frontend - 
image
image

Will update as you suggested :+1:

**Comment by liveHarshit** [comment]
Updated

**Comment by iamareebjamal** [comment]
OK, I thought it displayed like that in frontend. Please stick with the way frontend shows it

**Comment by liveHarshit** [comment]
> OK, I thought it displayed like that in frontend. Please stick with the way frontend shows it

But frontend is not displaying ticket price details. It is according to the Eventbrite. So that is correct imo

**Pull request merged**
