### PR TITLE
WIP - Set up sending/editting proposal for speakers call

### LINKED ISSUE #1880: Set up sending proposals for speakers call
**Describe the feature you'd like**
Set up sending proposals for speakers call + Editting current proposal

**Additional context**
Continuity from #1816 

**Would you like to work on the issue?**
Yes

### PR DESCRIPTION
**Pull request by anhanh11001**
Fixes #1880 
Work Left:
- Set up right query with network call to fetch current session proposed.
- Update fetching cached sessions/speakers from the database 
- Test update/create sessions proposal

Screenshots for the change:
Add later

### CODE REVIEW

**Comment by anhanh11001** [comment]
I'm having problem making POST/PATCH request to create/update sessions under user with this error. Please give some advices:

**Making updates: PATCH/v1/sessions/{session_id}**
```
D/OkHttp: Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NTk5MzIyMDAsImlhdCI6MTU1OTg0NTgwMCwibmJmIjoxNTU5ODQ1ODAwLCJpZGVudGl0eSI6NzYyMn0.vrImL-LPXamU9xG8QZ0yWjPW3NFG9nCzkWH3LZ_bIqA
    {"data":{"type":"session","id":"5328","attributes":{"short-abstract":"This session will answer questions of what is FOSS, what's so good about it and how to join in the open-source community.","comments":"","long-abstract":null,"level":null,"signup-url":null,"ends-at":null,"language":"","title":"Introduction to Open Source Community","starts-at":null,"slides-url":null,"average-rating":null,"submitted-at":null,"deleted-at":null,"subtitle":null,"created-at":null,"state":null,"last-modified-at":null,"video-url":null,"audio-url":null,"session-type":{"id":709,"name":"Discussion","length":"00:30","deleted-at":null}},"relationships":{"event":{"data":{"type":"event","id":"827"}},"session-type":{"data":{"type":"session-type","id":"709"}},"track":{"data":{"type":"track","id":"1247"}}}}}
    --> END PATCH (787-byte body)
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, egl_color_buffer_format *, EGLBoolean) returns 0x3000
D/OpenGLRenderer:   HWUI Binary is  enabled
D/OkHttp: <-- 500 https://api.eventyay.com/v1/sessions/5328 (250ms)
D/OkHttp: date: Thu, 06 Jun 2019 18:50:22 GMT
    content-type: application/vnd.api+json
    content-length: 140
    set-cookie: __cfduid=d99b6172394fac620341b892c2f0db5911559847022; expires=Fri, 05-Jun-20 18:50:22 GMT; path=/; domain=.eventyay.com; HttpOnly
    access-control-allow-origin: *
    expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
    server: cloudflare
    cf-ray: 4e2c92529f2a732f-AMS
D/OkHttp: {"errors": [{"detail": "Unknown error", "source": {"pointer": ""}, "status": 500, "title": "Unknown error"}], "jsonapi": {"version": "1.0"}}
    <-- END HTTP (140-byte body)
W/libEGL: EGLNativeWindowType 0x7d441f7010 disconnect failed
E/SpeakersCallProposalViewModel$editProposal: Fail on updating session 5328
    retrofit2.adapter.rxjava2.HttpException: HTTP 500 
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

**Creating session: POST/v1/sessions{?sort,filter}**
```
D/OkHttp: --> POST https://api.eventyay.com/v1/sessions
    Content-Type: application/vnd.api+json
    Content-Length: 493
    Authorization: JWT eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1NTk5MzIyMDAsImlhdCI6MTU1OTg0NTgwMCwibmJmIjoxNTU5ODQ1ODAwLCJpZGVudGl0eSI6NzYyMn0.vrImL-LPXamU9xG8QZ0yWjPW3NFG9nCzkWH3LZ_bIqA
    {"data":{"type":"session","id":"7622","attributes":{"short-abstract":"","comments":"","long-abstract":null,"level":null,"signup-url":null,"ends-at":null,"language":"English","title":"Discussion Open Source","starts-at":null,"slides-url":null,"average-rating":null,"submitted-at":null,"deleted-at":null,"subtitle":null,"created-at":null,"state":null,"last-modified-at":null,"video-url":null,"audio-url":null,"session-type":null},"relationships":{"track":{"data":{"type":"track","id":"1248"}}}}}
    --> END POST (493-byte body)
D/OkHttp: <-- 404 https://api.eventyay.com/v1/sessions (89ms)
    date: Thu, 06 Jun 2019 18:44:58 GMT
    content-type: application/vnd.api+json
    set-cookie: __cfduid=d58aaecadf803977bae58a3003f1d025c1559846698; expires=Fri, 05-Jun-20 18:44:58 GMT; path=/; domain=.eventyay.com; HttpOnly
    access-control-allow-origin: *
    expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
    server: cloudflare
    cf-ray: 4e2c8a6a6a3e732f-AMS
D/OkHttp: {"errors": [{"status": 404, "source": {"parameter": "{id}"}, "title": "Object not found", "detail": "Session: not found"}], "jsonapi": {"version": "1.0"}}
D/OkHttp: <-- END HTTP (154-byte body)
W/libEGL: EGLNativeWindowType 0x7d6e539010 disconnect failed
E/SpeakersCallProposalViewModel$submitProposal: Fail on creating new session
    retrofit2.adapter.rxjava2.HttpException: HTTP 404 
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:54)
        at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:37)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
        at io.reactivex.Single.subscribe(Single.java:3603)
        at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:784)
```

**Comment by iamareebjamal** [comment]
When you're creating a session, how can you send an ID?

**Comment by iamareebjamal** [comment]
About the patch request, open an issue on the server

**Comment by anhanh11001** [comment]
@iamareebjamal I'm not sure if I understand your question about sending ID (what's exactly you means by ID)? So I created Session object by this:
```
val proposal = Session(
                    id = speakersCallProposalViewModel.session.value?.id ?: speakersCallProposalViewModel.getId(), // from authHolder
                    title = rootView.title.text.toString(),
                    language = rootView.language.text.toString(),
                    shortAbstract = rootView.shortAbstract.text.toString(),
                    comments = rootView.comment.text.toString(),
                    sessionType = sessionTypesList[speakersCallProposalViewModel.sessionTypePosition],
                    track = tracksList[speakersCallProposalViewModel.trackPosition],
                    event = EventId(safeArgs.eventId)
                )
                if (isAddingNewSession)
                    speakersCallProposalViewModel.submitProposal(proposal)
                else
                    speakersCallProposalViewModel.editProposal(safeArgs.sessionId, proposal)
```

**Comment by iamareebjamal** [comment]
```
id = speakersCallProposalViewModel.session.value?.id ?: speakersCallProposalViewModel.getId(), // from authHolder
```

You cannot send ID of the entity you are creating. Please see the doc body and match it bit by bit

**Comment by anhanh11001** [comment]
Closing as I made some problem with my old forked repo so I have to fork a new one earlier this week, I'm sending a new PR on this issue

**Pull request closed without merging**
