### PR TITLE
chore(deps): bump gradle from 3.5.3 to 3.6.3

### PR DESCRIPTION
**Pull request by adityastic**
Fixes #2688

### CODE REVIEW

**Comment by adityastic** [comment]
@iamareebjamal this is weird, check both the builds, the lint issues contradict the latest build:
Lint Issue Build: https://travis-ci.org/github/fossasia/open-event-attendee-android/builds/682850027
Fixed Build: https://travis-ci.org/github/fossasia/open-event-attendee-android/builds/682861305

<blockquote><div><strong><a href="https://travis-ci.org/github/fossasia/open-event-attendee-android/builds/682850027">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div><div>Travis CI enables your team to test and ship your apps with confidence. Easily sync your projects with Travis CI and you'll be testing your code in minutes.</div></blockquote>
<blockquote><div><strong><a href="https://travis-ci.org/github/fossasia/open-event-attendee-android/builds/682861305">Travis CI - Test and Deploy Your Code with Confidence</a></strong></div><div>Travis CI enables your team to test and ship your apps with confidence. Easily sync your projects with Travis CI and you'll be testing your code in minutes.</div></blockquote>

**Comment by iamareebjamal** [comment]
Maybe due to change in gradle plugin

**Comment by adityastic** [comment]
@iamareebjamal RTM

**Review by iamareebjamal — APPROVED** [review]
Thanks a lot

**Pull request merged**
